


--////////////////////////////////////////////////////////////////////////////// basic modify
/*
theBox = box position:[0,0,0] height:100 heightsegs:50
mytwist = twist angle:90

addmodifier theBox mytwist
addmodifier theBox (bend angle:50)

theBox.modifiers.count
theBox.modifiers[1].name
*/






--////////////////////////////////////////////////////////////////////////////// basic modify

--addmodifier
--deletemodifier $ 1
--collapsestack $







